# -*- mode: ruby -*-
# vi: set ft=ruby :
def install_plugin(plugin)
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

install_plugin('vagrant-vbguest')

boxs = {
  centos7: 'centos/7',
  xenial: 'ubuntu/xenial64'
}

Vagrant.configure('2') do |config|
  boxs.each do |name, box|
    config.vm.define name do |c|
      c.vm.box = box
    end
  end

  config.vm.box_check_update = true

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "#{ENV['HOME']}/src", '/home/vagrant/src'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = '4096'
  end
end
