# -*- mode: ruby -*-
# vi: set ft=ruby :
def install_plugin(plugin)
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

install_plugin('vagrant-vbguest')

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/bionic64'

  config.vm.box_check_update = true

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "#{ENV['HOME']}/src", '/home/vagrant/src'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'haconiwa-build'
    vb.gui = false
    vb.cpus = 2
    vb.memory = '4096'
    vb.customize ['setextradata', :id, 'VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled', 0]
  end

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq util-linux rake psmisc bison git gperf cgroup-lite libpam0g-dev autotools-dev libcap-dev libargtable2-dev parallel automake autoconf libtool flex
  SHELL
end
